export const TYPES = {
    READ_STATES: "READ_STATES",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_TO_CART: "REMOVE_TO_CART",
    REMOVE_ALL_TO_CART: "REMOVE_ALL_TO_CART",
    DELETE_CART: "DELETE_CART"
}